"""add risk source column

Revision ID: 21824ec0933b
Revises: cf7f92f27fe3
Create Date: 2026-07-14 12:04:14.204614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21824ec0933b'
down_revision: Union[str, Sequence[str], None] = 'cf7f92f27fe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risks', sa.Column('source', sa.String(), server_default=sa.text("'manual'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risks', 'source')
    # ### end Alembic commands ###
