"""add plugin enrichment cache

Revision ID: 3149b9827486
Revises: c0553e37bb5d
Create Date: 2026-07-13 14:44:47.486868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3149b9827486'
down_revision: Union[str, Sequence[str], None] = 'c0553e37bb5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugin_enrichment_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plugin_id', sa.String(), nullable=False),
    sa.Column('cve_ids', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plugin_enrichment_cache'))
    )
    op.create_index(op.f('ix_plugin_enrichment_cache_id'), 'plugin_enrichment_cache', ['id'], unique=False)
    op.create_index(op.f('ix_plugin_enrichment_cache_plugin_id'), 'plugin_enrichment_cache', ['plugin_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plugin_enrichment_cache_plugin_id'), table_name='plugin_enrichment_cache')
    op.drop_index(op.f('ix_plugin_enrichment_cache_id'), table_name='plugin_enrichment_cache')
    op.drop_table('plugin_enrichment_cache')
    # ### end Alembic commands ###
