"""add epss score cache

Revision ID: 65fe339a2f7c
Revises: d47a9c3e6f18
Create Date: 2026-07-16 16:11:11.417663

Adds the epss_score_cache table caching FIRST.org EPSS lookups (one
row per CVE, refreshed on a 24h TTL even on success since EPSS scores
are recomputed daily - see app/services/enrichment/epss_enrichment.py).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65fe339a2f7c'
down_revision: Union[str, Sequence[str], None] = 'd47a9c3e6f18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epss_score_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.String(), nullable=False),
    sa.Column('epss_score', sa.Float(), nullable=True),
    sa.Column('percentile', sa.Float(), nullable=True),
    sa.Column('score_date', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_epss_score_cache'))
    )
    op.create_index(op.f('ix_epss_score_cache_cve_id'), 'epss_score_cache', ['cve_id'], unique=True)
    op.create_index(op.f('ix_epss_score_cache_id'), 'epss_score_cache', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_epss_score_cache_id'), table_name='epss_score_cache')
    op.drop_index(op.f('ix_epss_score_cache_cve_id'), table_name='epss_score_cache')
    op.drop_table('epss_score_cache')
    # ### end Alembic commands ###
