"""baseline schema

Revision ID: c0553e37bb5d
Revises: 
Create Date: 2026-07-13 13:47:43.665452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0553e37bb5d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('criticality', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('environment', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_table('frameworks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('publisher', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_frameworks')),
    sa.UniqueConstraint('short_name', name=op.f('uq_frameworks_short_name'))
    )
    op.create_index(op.f('ix_frameworks_id'), 'frameworks', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('framework_id', sa.Integer(), nullable=False),
    sa.Column('category_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['framework_id'], ['frameworks.id'], name=op.f('fk_categories_framework_id_frameworks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('impact', sa.Integer(), nullable=False),
    sa.Column('likelihood', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_risks_asset_id_assets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risks'))
    )
    op.create_index(op.f('ix_risks_id'), 'risks', ['id'], unique=False)
    op.create_table('controls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('implementation_guidance', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_controls_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_controls')),
    sa.UniqueConstraint('control_id', name=op.f('uq_controls_control_id'))
    )
    op.create_index(op.f('ix_controls_id'), 'controls', ['id'], unique=False)
    op.create_table('vulnerabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('plugin_id', sa.String(), nullable=True),
    sa.Column('cve_id', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('solution', sa.String(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('risk_id', sa.Integer(), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_vulnerabilities_asset_id_assets')),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], name=op.f('fk_vulnerabilities_risk_id_risks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vulnerabilities'))
    )
    op.create_index(op.f('ix_vulnerabilities_id'), 'vulnerabilities', ['id'], unique=False)
    op.create_table('vulnerability_control_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vulnerability_id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.String(), nullable=True),
    sa.Column('matched_value', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], name=op.f('fk_vulnerability_control_mappings_control_id_controls')),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], name=op.f('fk_vulnerability_control_mappings_vulnerability_id_vulnerabilities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vulnerability_control_mappings'))
    )
    op.create_index(op.f('ix_vulnerability_control_mappings_id'), 'vulnerability_control_mappings', ['id'], unique=False)
    op.create_table('mapping_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mapping_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('previous_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['mapping_id'], ['vulnerability_control_mappings.id'], name=op.f('fk_mapping_history_mapping_id_vulnerability_control_mappings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mapping_history'))
    )
    op.create_index(op.f('ix_mapping_history_id'), 'mapping_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mapping_history_id'), table_name='mapping_history')
    op.drop_table('mapping_history')
    op.drop_index(op.f('ix_vulnerability_control_mappings_id'), table_name='vulnerability_control_mappings')
    op.drop_table('vulnerability_control_mappings')
    op.drop_index(op.f('ix_vulnerabilities_id'), table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_index(op.f('ix_controls_id'), table_name='controls')
    op.drop_table('controls')
    op.drop_index(op.f('ix_risks_id'), table_name='risks')
    op.drop_table('risks')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_frameworks_id'), table_name='frameworks')
    op.drop_table('frameworks')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
